### ISSUE TITLE
Permissions must be set when registering a user

### ISSUE THREAD

**Issue by mohameddahrouj** [tosinoni/SECP#114]

**Comment by mohameddahrouj** [comment]
@tosinoni, are you suggesting we add a permission level and role field to the register form?

**Comment by tosinoni** [comment]
Only the permission field. A user must have a permission. So let’s include a permission select2 in the register modal.

**Comment by mohameddahrouj** [comment]
This has been completed in Issue #124. Commit hash: 9e59c624fcd7a328ea9ee3cc86662cd00c6e0395
